--------------------------------------------------------------------------------------------------------------------------
-- LocalisedText
--------------------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO LocalizedText
		(Tag, 								Language,	Text)
VALUES
-- English US ------------------------------------------------------------------------------------------------------------
		("LOC_CHEAT_MENU_ABOUT",  					"en_US",		"Cheat Panel By [Sparrow]"),
		("LOC_CHEAT_EXPAND_MAX",  					"en_US",		"Hide Advanced Panel"),
		("LOC_CHEAT_COLLAPSE_MAX",  				"en_US",		"Show Advanced Panel"),
		("LOC_FORM_ARMY",  							"en_US",		"Form an Army/Armada From Selected Unit"),
		("LOC_FORM_CORPS",  						"en_US",		"Form an Corps/Fleet From Selected Unit"),
		("LOC_CHEAT_MENU_DIPLOMATIC_FAVOR", 		"en_US",		"Adds +100  Diplomatic Favor"),
		("LOC_CHEAT_MENU_HEADER",  					"en_US",		"CHEAT PANEL"),
		("LOC_CHEAT_TOGGLE_MENU",  					"en_US",		"Toggle Cheat Panel"),
		("LOC_CHEAT_ICON",  						"en_US",		"Cheat Menu By Sparrow"),
		("LOC_CHEAT_MENU_GOVPOINTS",  				"en_US",		"Adds +1 Governor Title Point"),
		("LOC_CHEAT_MENU_GOLD",  					"en_US",		"Adds +1000 [ICON_Gold]"),
		("LOC_CHEAT_MENU_PRODUCTION",  				"en_US",		"Completes Current [ICON_Production] in Selected City"),
		("LOC_CHEAT_MENU_SCIENCE",  				"en_US",		"Completes Current Research [ICON_Science]"),
		("LOC_CHEAT_MENU_CULTURE",  				"en_US",		"Completes Current Civic [ICON_Culture]"),
		("LOC_CHEAT_MENU_FAITH",  					"en_US",		"Adds +1000 [ICON_Faith]"),
		("LOC_CHEAT_MENU_ENVOY",  					"en_US",		"Adds +5 [ICON_Envoy] Envoy"),
		("LOC_CHEAT_MENU_ERA",  					"en_US",		"Increase Era Points +10"),
		("LOC_CHEAT_MENU_ERAMINUS",  				"en_US",		"Decrease Era Points -10"),
		("LOC_CHEAT_MENU_MOVE",  					"en_US",		"Add +5  Movement to Selected Unit"),
		("LOC_CHEAT_MENU_XP",  						"en_US",		"Give Promotion to Selected Unit"),
		("LOC_CHEAT_MENU_HEAL",  					"en_US",		"Heals Selected Unit"),
		("LOC_CHEAT_MENU_MOVES",  					"en_US",		"Restores Unit Movement [ICON_Movement]"),
		("LOC_CHEAT_MENU_DUPLICATE",  				"en_US",		"Duplicate Selected Unit"),
		("LOC_CHEAT_MENU_POP",  					"en_US",		"Adds +1 [ICON_Citizen] to Selected City"),
		("LOC_CHEAT_MENU_LOYALTY",  				"en_US",		"Adds +100  Loyalty to Selected City"),
		("LOC_CHEAT_MENU_DESTROY",  				"en_US",		"Destroy City"),
		("LOC_CHEAT_MENU_CITYHEAL",  				"en_US",		"Repair City GARRISON & OUTTER WALLS"),
		("LOC_CHEAT_MENU_AllTECH",  				"en_US",		"All [ICON_Science]"),
		("LOC_CHEAT_MENU_AllCIVIC",  				"en_US",		"All [ICON_Culture]"),
		("LOC_CHEAT_MENU_AllTECH_TOOLTIP",  		"en_US",		"Complete All [ICON_Science]"),
		("LOC_CHEAT_MENU_AllCIVIC_TOOLTIP",  		"en_US",		"Complete All [ICON_Culture]"),
		("LOC_CHEAT_MENU_OBVS",  					"en_US",		"Toggle Map Observer"),
		("LOC_DESTROY_CITY_HEADER",  				"en_US",		"Raze Selected City"),
		("LOC_DESTROY_CITY_DISTRICTS_LABEL",  		"en_US",		"Districts:"),
		("LOC_RAZE_CITY_EXPLANATION",				"en_US",		"Raze city clearing it and all its districts and buildings from the map."),
		("LOC_KEEP_CITY_EXPLANATION",				"en_US",		"Keep this city in your empire for now."),
		("LOC_DESTROY_CITY_LIBERATE_EXPLANATION",	"en_US",		"Liberating a city will return it to one of their previous owners, possibly bringing that civilization back into the game."),
		
-- Italian --------------------------------------------------------------------------------------------------
		("LOC_CHEAT_MENU_ABOUT",  					"it_IT",		"Cheat Panel By [Sparrow]"),
		("LOC_CHEAT_EXPAND_MAX",  					"it_IT",		"Hide Advanced Panel"),
		("LOC_CHEAT_COLLAPSE_MAX",  				"it_IT",		"Show Advanced Panel"),
		("LOC_FORM_ARMY",  							"it_IT",		"Form an Army/Armada From Selected Unit"),
		("LOC_FORM_CORPS",  						"it_IT",		"Form an Corps/Fleet From Selected Unit"),
		("LOC_CHEAT_MENU_DIPLOMATIC_FAVOR", 		"it_IT",		"Adds +100  Diplomatic Favor"),
		("LOC_CHEAT_TOGGLE_MENU", 					"it_IT", 		"Attiva cheat Panel"),
		("LOC_CHEAT_ICON", 							"it_IT",		"Cheat Menu By Sparrow"),
		("LOC_CHEAT_MENU_GOVPOINTS", 				"it_IT",		"Aggiunge un +1 al punto di titolo del governatore"),
		("LOC_CHEAT_MENU_GOLD", 					"it_IT", 		"Aggiunge +1000 [ICON_Gold]"),
		("LOC_CHEAT_MENU_PRODUCTION", 				"it_IT", 		"Completa la corrente [ICON_Production] nella città selezionata"),
		("LOC_CHEAT_MENU_SCIENCE", 					"it_IT", 		"Completa la ricerca corrente [ICON_Science]"),
		("LOC_CHEAT_MENU_CULTURE", 					"it_IT", 		"Completes Current Civic [ICON_Culture]"),
		("LOC_CHEAT_MENU_FAITH", 					"it_IT", 		"Aggiunge +1000 [ICON_Faith]"),
		("LOC_CHEAT_MENU_ENVOY", 					"it_IT",		"Aggiunge +5 [ICON_Envoy] Envoy"),
		("LOC_CHEAT_MENU_ERA", 						"it_IT", 		"Aggiunge +10 punti epoca"),
		("LOC_CHEAT_MENU_MOVE", 					"it_IT",		"Aggiungi +5 movimento all'unità selezionata"),
		("LOC_CHEAT_MENU_XP", 						"it_IT", 		"Invia la promozione all'unità selezionata"),
		("LOC_CHEAT_MENU_HEAL", 					"it_IT",		"Cura l'unità selezionata"),
		("LOC_CHEAT_MENU_MOVES", 					"it_IT", 		"Ripristina movimento unità [ICON_Movement]"),
		("LOC_CHEAT_MENU_DUPLICATE", 				"it_IT", 		"Duplica unità selezionata"),
		("LOC_CHEAT_MENU_POP", 						"it_IT", 		"Aggiunge +1 [ICON_Citizen] alla città selezionata"),
		("LOC_CHEAT_MENU_LOYALTY", 					"it_IT", 		"Aggiunge +100 fedeltà alla città selezionata"),
		("LOC_CHEAT_MENU_DESTROY", 					"it_IT", 		"Distrugge la città selezionata"),
		("LOC_CHEAT_MENU_AllTECH", 					"it_IT", 		"Completa tutto [ICON_Science]"),
		("LOC_CHEAT_MENU_AllCIVIC", 				"it_IT", 		"Completa tutto [ICON_Culture]"),
		("LOC_CHEAT_MENU_OBVS", 					"it_IT", 		"Attiva / disattiva mappa osservatore"),
		("LOC_DESTROY_CITY_HEADER", 				"it_IT", 		"Raze Selected City"),
		("LOC_DESTROY_CITY_DISTRICTS_LABEL", 		"it_IT", 		"Distretti:"),
		("LOC_RAZE_CITY_EXPLANATION", 				"it_IT", 		"Raze City che cancella la mappa e tutti i suoi distretti e edifici dalla mappa."),
		("LOC_KEEP_CITY_EXPLANATION", 				"it_IT", 		"Tieni questa città nel tuo impero per ora."),
		("LOC_DESTROY_CITY_LIBERATE_EXPLANATION", 	"it_IT", 		"Liberare una città lo restituirà a uno dei loro precedenti proprietari, probabilmente riportando la civiltà in gioco."),

-- Russian RU ------------------------------------------------------------------------------------------------------------
        ("LOC_CHEAT_MENU_ABOUT",                    "ru_RU",        "Чит Панель от [Sparrow]"),
        ("LOC_CHEAT_EXPAND_MAX",                    "ru_RU",        "Спрятать Расширенную Панель"),
        ("LOC_CHEAT_COLLAPSE_MAX",                  "ru_RU",        "Показать Расширенную Панель"),
        ("LOC_FORM_ARMY",                           "ru_RU",        "Образовать Армию/Армаду из выбранного юнита"),
        ("LOC_FORM_CORPS",                          "ru_RU",        "Образовать Корпус/Флот из выбранного юнита"),
        ("LOC_CHEAT_MENU_DIPLOMATIC_FAVOR",         "ru_RU",        "Добавить +100 Дип. одолжения"),
        ("LOC_CHEAT_MENU_HEADER",                   "ru_RU",        "ЧИТ ПАНЕЛЬ"),
        ("LOC_CHEAT_TOGGLE_MENU",                   "ru_RU",        "Вкл/выкл Чит Панель"),
        ("LOC_CHEAT_ICON",                          "ru_RU",        "Чит меню от Sparrow"),
        ("LOC_CHEAT_MENU_GOVPOINTS",                "ru_RU",        "Добавить +1 титул Губернатора"),
        ("LOC_CHEAT_MENU_GOLD",                     "ru_RU",        "Добавить +1000 [ICON_Gold]"),
        ("LOC_CHEAT_MENU_PRODUCTION",               "ru_RU",        "Завершить текущую [ICON_Production] в выбранном городе"),
        ("LOC_CHEAT_MENU_SCIENCE",                  "ru_RU",        "Завершить текущую Технологию [ICON_Science]"),
        ("LOC_CHEAT_MENU_CULTURE",                  "ru_RU",        "Завершить текущий Социальный институт [ICON_Culture]"),
        ("LOC_CHEAT_MENU_FAITH",                    "ru_RU",        "Добавить +1000 [ICON_Faith]"),
        ("LOC_CHEAT_MENU_ENVOY",                    "ru_RU",        "Добавить +5 [ICON_Envoy] эмиссаров"),
        ("LOC_CHEAT_MENU_ERA",                      "ru_RU",        "Увеличить очки Эры на +10"),
        ("LOC_CHEAT_MENU_ERAMINUS",                 "ru_RU",        "Уменьшить очки Эры на -10"),
        ("LOC_CHEAT_MENU_MOVE",                     "ru_RU",        "Добавить +5 ед. движения выбранному юниту"),
        ("LOC_CHEAT_MENU_XP",                       "ru_RU",        "Повысить в звании выбранный юнит"),
        ("LOC_CHEAT_MENU_HEAL",                     "ru_RU",        "Восстановить выбранный юнит"),
        ("LOC_CHEAT_MENU_MOVES",                    "ru_RU",        "Восстановить очки движения [ICON_Movement]"),
        ("LOC_CHEAT_MENU_DUPLICATE",                "ru_RU",        "Скопировать выбранный юнит"),
        ("LOC_CHEAT_MENU_POP",                      "ru_RU",        "Добавить +1 [ICON_Citizen] в выбранном городе"),
        ("LOC_CHEAT_MENU_LOYALTY",                  "ru_RU",        "Добавить +100  Лояльности в выбранном городе"),
        ("LOC_CHEAT_MENU_DESTROY",                  "ru_RU",        "Уничтожить город"),
        ("LOC_CHEAT_MENU_CITYHEAL",                 "ru_RU",        "Восстановить Гарризон и Стены выбранного города"),
        ("LOC_CHEAT_MENU_AllTECH",                  "ru_RU",        "Все [ICON_Science]"),
        ("LOC_CHEAT_MENU_AllCIVIC",                 "ru_RU",        "Все [ICON_Culture]"),
        ("LOC_CHEAT_MENU_AllTECH_TOOLTIP",          "ru_RU",        "Завершить все [ICON_Science]"),
        ("LOC_CHEAT_MENU_AllCIVIC_TOOLTIP",         "ru_RU",        "Завершить все [ICON_Culture]"),
        ("LOC_CHEAT_MENU_OBVS",                     "ru_RU",        "Вкл/выкл Режим Наблюдателя"),
        ("LOC_DESTROY_CITY_HEADER",                 "ru_RU",        "Снести выбранный город"),
        ("LOC_DESTROY_CITY_DISTRICTS_LABEL",        "ru_RU",        "Районы:"),
        ("LOC_RAZE_CITY_EXPLANATION",               "ru_RU",        "Снести город вмести со всеми районами и строениями."),
        ("LOC_KEEP_CITY_EXPLANATION",               "ru_RU",        "Присоединить город к вашей империи"),
        ("LOC_DESTROY_CITY_LIBERATE_EXPLANATION",   "ru_RU",        "Освобождение города вернет его  предыдущему владельцу, возможно, восстанавливая эту цивилизацию в игре."),

-- Chinese (simplified)---------------------------------------------------------------------------------------------------------------
		("LOC_CHEAT_MENU_ABOUT",  					"zh_Hans_CN",	"Cheat Panel By [Sparrow]"),
		("LOC_CHEAT_EXPAND_MAX",  					"zh_Hans_CN",	"Hide Advanced Panel"),
		("LOC_CHEAT_COLLAPSE_MAX",  				"zh_Hans_CN",	"Show Advanced Panel"),
		("LOC_FORM_ARMY",  							"zh_Hans_CN",	"所选单位升级为军队"),
		("LOC_FORM_CORPS",  						"zh_Hans_CN",	"Form an Corps/Fleet From Selected Unit"),
		("LOC_CHEAT_MENU_DIPLOMATIC_FAVOR", 		"zh_Hans_CN",	"加+100外交支持"),
		("LOC_CHEAT_TOGGLE_MENU",					"zh_Hans_CN",	"切换作弊面板"),
		("LOC_CHEAT_ICON",							"zh_Hans_CN",	"麻雀作弊菜单"),
		("LOC_CHEAT_MENU_GOVPOINTS",				"zh_Hans_CN",	"加+1总督头衔"),
		("LOC_CHEAT_MENU_GOLD",						"zh_Hans_CN",	"加+100金币"),
		("LOC_CHEAT_MENU_PRODUCTION",				"zh_Hans_CN",	"所选城市完成当前建筑"),
		("LOC_CHEAT_MENU_SCIENCE",					"zh_Hans_CN",	"完成当前科技研究"),
		("LOC_CHEAT_MENU_CULTURE",					"zh_Hans_CN",	"完成当前市政研究"),
		("LOC_CHEAT_MENU_FAITH",					"zh_Hans_CN",	"加+100信仰"),
		("LOC_CHEAT_MENU_ENVOY",					"zh_Hans_CN",	"加+5使者"),
		("LOC_CHEAT_MENU_ERA",						"zh_Hans_CN",	"加+10时代得分"),
		("LOC_CHEAT_MENU_MOVE",						"zh_Hans_CN",	"所选单位加+5移动力"),
		("LOC_CHEAT_MENU_XP",						"zh_Hans_CN",	"促销选定单位"),
		("LOC_CHEAT_MENU_HEAL",						"zh_Hans_CN",	"治愈所选单位"),
		("LOC_CHEAT_MENU_MOVES",					"zh_Hans_CN",	"所选单位恢复行动+攻击"),
		("LOC_CHEAT_MENU_DUPLICATE",				"zh_Hans_CN",	"复制所选的单位（不适用于伟人和宗教单位）"),
		("LOC_CHEAT_MENU_POP",						"zh_Hans_CN",	"所选城市加+1人口"),
		("LOC_CHEAT_MENU_LOYALTY",					"zh_Hans_CN",	"所选城市加满忠诚度 "),
		("LOC_CHEAT_MENU_DESTROY",					"zh_Hans_CN",	"销毁选定城市"),
		("LOC_CHEAT_MENU_AllTECH",					"zh_Hans_CN",	"完成所有科技研究"),
		("LOC_CHEAT_MENU_AllCIVIC",					"zh_Hans_CN",	"完成所有市政研究"),
		("LOC_CHEAT_MENU_OBVS",						"zh_Hans_CN",	"切换地图观察模式"),
		("LOC_DESTROY_CITY_HEADER",					"zh_Hans_CN",	"Raze精选城市"),
		("LOC_DESTROY_CITY_DISTRICTS_LABEL",		"zh_Hans_CN",	"地区："),
		("LOC_RAZE_CITY_EXPLANATION",				"zh_Hans_CN",	"摧毁所选城市"),
		("LOC_KEEP_CITY_EXPLANATION",				"zh_Hans_CN",	"暂时将这座城市留在你的帝国。"),
		("LOC_DESTROY_CITY_LIBERATE_EXPLANATION",	"zh_Hans_CN",	"解放一个城市将把它归还给他们之前的一个所有者,	可能会把这个文明带回游戏中。");
		
-- Japanese ------------------------------------------------------------------------------------------------------------
		("LOC_CHEAT_MENU_ABOUT",  					"ja_JP",		"Cheat Panel By [Sparrow]"),
		("LOC_CHEAT_EXPAND_MAX",  					"ja_JP",		"Hide Advanced Panel"),
		("LOC_CHEAT_COLLAPSE_MAX",  				"ja_JP",		"Show Advanced Panel"),
		("LOC_FORM_ARMY",  							"ja_JP",		"所选单位升级为军队"),
		("LOC_FORM_CORPS",  						"ja_JP",		"所选单位升级为军团"),
		("LOC_CHEAT_MENU_DIPLOMATIC_FAVOR", 		"ja_JP",		"加+100外交支持"),
		("LOC_CHEAT_EXPAND_MAX",  					"ja_JP",		"詳細パネルを隠す"),
		("LOC_CHEAT_COLLAPSE_MAX",  				"ja_JP",		"詳細パネルの表示"),
		("LOC_FORM_ARMY",  							"ja_JP",		"選択中のユニットを大軍団/大艦隊にする"),
		("LOC_FORM_CORPS",  						"ja_JP",		"選択中のユニットを軍団/艦隊にする"),
		("LOC_CHEAT_MENU_DIPLOMATIC_FAVOR", 		"ja_JP",		"影響力ポイントを追加 +100"),
		("LOC_CHEAT_MENU_HEADER",  					"ja_JP",		"チートパネル"),
		("LOC_CHEAT_TOGGLE_MENU",  					"ja_JP",		"チートパネルの表示切り替え"),
		("LOC_CHEAT_MENU_GOVPOINTS",  				"ja_JP",		"総督の称号を追加 +1"),
		("LOC_CHEAT_MENU_GOLD",  					"ja_JP",		"ゴールドを追加 +1000 [ICON_Gold]"),
		("LOC_CHEAT_MENU_PRODUCTION",  				"ja_JP",		"選択中の都市の生産完了 [ICON_Production]"),
		("LOC_CHEAT_MENU_SCIENCE",  				"ja_JP",		"研究完了 [ICON_Science]"),
		("LOC_CHEAT_MENU_CULTURE",  				"ja_JP",		"社会制度完了 [ICON_Culture]"),
		("LOC_CHEAT_MENU_FAITH",  					"ja_JP",		"信仰を追加 +1000 [ICON_Faith]"),
		("LOC_CHEAT_MENU_ENVOY",  					"ja_JP",		"代表団を追加 +5 [ICON_Envoy] Envoy"),
		("LOC_CHEAT_MENU_ERA",  					"ja_JP",		"時代スコアを加算 +10"),
		("LOC_CHEAT_MENU_ERAMINUS",  				"ja_JP",		"時代スコアを減算 -10"),
		("LOC_CHEAT_MENU_MOVE",  					"ja_JP",		"ユニットの移動力を追加 +5"),
		("LOC_CHEAT_MENU_XP",  						"ja_JP",		"選択中のユニットをレベルアップ"),
		("LOC_CHEAT_MENU_HEAL",  					"ja_JP",		"選択中のユニットの体力を回復"),
		("LOC_CHEAT_MENU_MOVES",  					"ja_JP",		"ユニットを行動可能にする [ICON_Movement]"),
		("LOC_CHEAT_MENU_DUPLICATE",  				"ja_JP",		"選択中のユニットを複製"),
		("LOC_CHEAT_MENU_POP",  					"ja_JP",		"選択中の都市の人口を追加 +1 [ICON_Citizen]"),
		("LOC_CHEAT_MENU_LOYALTY",  				"ja_JP",		"選択中の都市の忠誠心を追加 +100"),
		("LOC_CHEAT_MENU_DESTROY",  				"ja_JP",		"選択中の都市を完全破壊"),
		("LOC_CHEAT_MENU_CITYHEAL",  				"ja_JP",		"選択中の都市の守備隊と防御施設の体力を回復"),
		("LOC_CHEAT_MENU_AllTECH_TOOLTIP",  		"ja_JP",		"全ての研究完了 [ICON_Science]"),
		("LOC_CHEAT_MENU_AllCIVIC_TOOLTIP",  		"ja_JP",		"全ての社会制度完了 [ICON_Culture]"),
		("LOC_CHEAT_MENU_OBVS",  					"ja_JP",		"「戦場の霧」の表示切り替え"),
		("LOC_DESTROY_CITY_HEADER",  				"ja_JP",		"都市を占領"),
		("LOC_DESTROY_CITY_DISTRICTS_LABEL",  		"ja_JP",		"区域:"),
		("LOC_RAZE_CITY_EXPLANATION",				"ja_JP",		"都市を完全に破壊し、すべての区域と建造物をマップから消滅させます。"),
		("LOC_KEEP_CITY_EXPLANATION",				"ja_JP",		"都市を破壊せず、占領状態を維持します。"),
		("LOC_DESTROY_CITY_LIBERATE_EXPLANATION",	"ja_JP",		"都市を解放し、以前の所有者に返還します。これにより、ゲームから脱落していた文明が復帰する可能性もあります。");